### PR TITLE
Add audit trail log view

### PR DESCRIPTION
**Pull request by jesperbrasmussen**
Hi Dan

I was missing the Audit Trail Log View in the v7 version, so I added it based on your code from the v8 version.

Here it is in case you find it in a good enough shape to merge into the v7 branch

Thanks
Jesper

### CODE REVIEW

**Comment by DanDiplo** [comment]
Cool, that's great - it was something I was thinking of doing. I'm a bit busy ATM but will look over this soon and, as I'm sure it will be great, I'll perform a new release. 

Do you happen to know which version of v7 the audit trail was added? So I can target the correct minimum Umbraco version?

**Comment by jesperbrasmussen** [comment]
Great. 
No sorry, don't know in which version the audit trail was added.

**Comment by DanDiplo** [comment]
Hi. I've tried this and the good news is the audit trail viewer works fine. But the bad news is that it replaces the current audit log viewer, which has now disappeared. Are you able to get it so both work in tandem, like v8?

**Comment by jesperbrasmussen** [comment]
> Hi. I've tried this and the good news is the audit trail viewer works fine. But the bad news is that it replaces the current audit log viewer, which has now disappeared. Are you able to get it so both work in tandem, like v8?

Yes i got it to work like this:

image

I have renamed the old audit log viewer to "Content Logs". Could that be what is causing trouble?

**Comment by DanDiplo** [comment]
Ahh, yes, that will be it! On my test install it added between another of my packages, so I never noticed. I probably just need to adjust the ordering of the tree and then mention about the renaming in the release notes!

But apart from that, everything seems to be working great. I'll hopefully release it sometime this week! Thanks.

image

**Comment by jesperbrasmussen** [comment]
That sound awesome. 
Looking forward to referencing your nuget package instead of my custom build.

**Comment by DanDiplo** [comment]
Hi @jesperbrasmussen I've uploaded this version to NuGet now: https://www.nuget.org/packages/Diplo.AuditLogViewer/1.1.0  

Can you test and make sure all is OK for you?

Sorry, I meant to credit you in the release notes, but inadvertently left in the ones from the previous version and NuGet won't let you edit :(  But hope you are happy :) I'll upload the Umbraco package version some time soon.

**Comment by jesperbrasmussen** [comment]
Never mind the Credits. I will be able to test it on friday

**Comment by jesperbrasmussen** [comment]
@DanDiplo Finally got around testing it. I referenced you NuGet ver. 1.1 instead, and it works fine for me :)

**Comment by DanDiplo** [comment]
@jesperbrasmussen Cool! It's worked for me on the sites I've tested, so I'm pretty confident all is OK. Just need to find time to update the Umbraco package now!

**Pull request merged**
